- name: Ensures /etc/docker dir exists
  become: yes
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
- name: docker config
  become: yes
  copy:
    dest: /etc/docker/daemon.json
    content: |-
      {
          "oom-score-adjust": -1000,
          "exec-opts": [
              "native.cgroupdriver=cgroupfs"
          ],
          "storage-driver": "overlay2",
          "storage-opts": [
              "overlay2.override_kernel_check=true"
          ],
          "log-driver": "json-file",
          "log-opts": {
              "max-size": "100m",
              "max-file": "3"
          },
          "max-concurrent-downloads": 10,
          "max-concurrent-uploads": 10,
          "registry-mirrors": [
              "https://lznzc04k.mirror.aliyuncs.com"
          ]
      }
- name: Install docker
  become: yes
  package:
    name:
      - docker-compose
      - docker.io
    state: present
