- name: Install miniconda
  script: scripts/install_miniconda.sh
- name: Ensures ~/.pip dir exists
  file:
    path: ~/.pip
    state: directory
- name: Copy pip.conf
  copy:
    src: config/home/.pip/pip.conf
    dest: ~/.pip/
- name: Copy .condarc
  copy:
    src: config/home/.condarc
    dest: ~/.condarc
- name: Install packages for Python development
  become: yes
  package:
    name:
      - gettext
      - libmysqlclient-dev
      - libyaml-dev
    state: present
