- name: Disable bell
  become: true
  command:
    cmd: sudo sed -i 's/# set bell-style none/set bell-style none/' /etc/inputrc
- name: Ensures ~/bin dir exists
  file:
    path: ~/bin
    state: directory
- name: Ensures ~/.profile.d dir exists
  file:
    path: ~/.profile.d
    state: directory
- name: Install required packages
  become: yes
  package:
    name:
      - build-essential
      - curl
      - direnv
      - fzf
      - git
      - git-extras
      - thefuck
      - tldr
    state: present
# https://github.com/Peltoche/lsd
- name: Install lsd
  become: yes
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/0.20.1/lsd_0.20.1_amd64.deb
- name: Install starship
  shell:
    cmd: bash -c "$(curl -fsSL https://starship.rs/install.sh)" "" -y -b ~/bin
- name: Copy starship config
  copy:
    src: config/home/.config/starship.toml
    dest: ~/.config/
- name: Install zsh
  become: yes
  package:
    name:
      - zsh
    state: present
- name: Ensures .oh-my-zsh dir absent
  file:
    path: ~/.oh-my-zsh
    state: absent
- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
- name: Change default shell to zsh
  shell:
    cmd: sudo chsh -s "$(command -v zsh)" "$(whoami)"
- name: Setup proxy env
  copy:
    dest: ~/.profile.d/proxy.sh
    content: |-
      export DEFAULT_PROXY="{{proxy}}"

      set_proxy() {
          export http_proxy=${DEFAULT_PROXY}
          export https_proxy=${DEFAULT_PROXY}
          export HTTP_PROXY=${DEFAULT_PROXY}
          export HTTPS_PROXY=${DEFAULT_PROXY}
      }

      unset_proxy() {
          unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY
      }

      set_proxy

- name: Copy .zshenv
  copy:
    src: config/home/.zshenv
    dest: ~/.zshenv
- name: Copy .zshrc
  copy:
    src: config/home/.zshrc
    dest: ~/.zshrc
