- name: yarn apt key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
- name: yarn apt repository
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn
- name: Install yarn
  become: yes
  package:
    name: yarn
    state: present
- name: Copy .npmrc
  copy:
    src: config/home/.npmrc
    dest: ~/.npmrc
- name: Setup web env
  copy:
    src: config/home/.profile.d/web.sh
    dest: ~/.profile.d/web.sh
