[aws]
disabled=true
[crystal]
disabled=true
[dotnet]
disabled=true
[elixir]
disabled=true
[elm]
disabled=true
[erlang]
disabled=true
[julia]
disabled=true
[kubernetes]
disabled=false
[nim]
disabled=true
[ocaml]
disabled=true
[php]
disabled=true
[zip]
disabled=true
